#7 Added an integration test for SaaS

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -91,7 +91,8 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        python-version: ["3.8", "3.9", "3.10", "3.11"]
+        # python-version: ["3.8", "3.9", "3.10", "3.11"]
+        python-version: ["3.10"]
         exasol-version: ["7.1.9"]
 
     steps:
@@ -104,6 +105,10 @@ jobs:
           python-version: ${{ matrix.python-version }}
 
       - name: Calculate Test Coverage
+        env:
+          SAAS_HOST: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_HOST }}
+          SAAS_ACCOUNT_ID: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID }}
+          SAAS_PAT: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_PAT }}
         run: poetry run nox -s coverage -- -- --db-version ${{ matrix.exasol-version }}
 
       - name: Upload Artifacts
@@ -111,3 +116,9 @@ jobs:
         with:
           name: .coverage
           path: .coverage
+
+      - name: Fail, if SaaS tests are not activated
+        if: "!contains(github.event.head_commit.message, '[run-saas-tests]') && (matrix.python-version == '3.10')"
+        run: |
+          echo "Failed because the SaaS tests are not activated"
+          exit 1
