#7 Trying a new TB feature

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -8,7 +8,7 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    
+
       - name: SCM Checkout
         uses: actions/checkout@v3
         with:
@@ -20,73 +20,9 @@ jobs:
       - name: Check Version(s)
         run: poetry run version-check version.py
 
-  build-documentation-job:
-    name: Build Documentation
-    needs: [version-check-job]
-    runs-on: ubuntu-latest
-
-    steps:
-    - name: SCM Checkout
-      uses: actions/checkout@v3
-
-    - name: Setup Python & Poetry Environment
-      uses: exasol/python-toolbox/.github/actions/python-environment@0.8.0
-
-    - name: Build Documentation
-      run: |
-        poetry run python -m nox -s build-docs
-
-  lint-job:
-    name: Linting (Python-${{ matrix.python-version }})
-    needs: [version-check-job]
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: ["3.8", "3.9", "3.10", "3.11"]
-
-    steps:
-      - name: SCM Checkout
-        uses: actions/checkout@v3
-
-      - name: Setup Python & Poetry Environment
-        uses: exasol/python-toolbox/.github/actions/python-environment@0.8.0
-        with:
-          python-version: ${{ matrix.python-version }}
-
-      - name: Run Tests
-        run: poetry run nox -s lint
-
-      - name: Upload Artifacts
-        uses: actions/upload-artifact@v3
-        with:
-          name: .lint.txt
-          path: .lint.txt
-
-  type-check-job:
-    name: Type Checking (Python-${{ matrix.python-version }})
-    needs: [version-check-job]
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: ["3.8", "3.9", "3.10", "3.11"]
-
-    steps:
-      - name: SCM Checkout
-        uses: actions/checkout@v3
-
-      - name: Setup Python & Poetry Environment
-        uses: exasol/python-toolbox/.github/actions/python-environment@0.8.0
-        with:
-          python-version: ${{ matrix.python-version }}
-
-      - name: Run Tests
-        run: poetry run nox -s type-check
-
   tests-job:
     name: Tests (Python-${{ matrix.python-version }}, Exasol-${{ matrix.exasol-version}})
-    needs: [build-documentation-job, lint-job, type-check-job]
+    # needs: [build-documentation-job, lint-job, type-check-job]
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -104,25 +40,21 @@ jobs:
         with:
           python-version: ${{ matrix.python-version }}
 
-      # - name: Calculate Test Coverage
-      #  run: poetry run nox -s coverage -- -- --db-version ${{ matrix.exasol-version }}
-
-      # - name: Upload Artifacts
-      #   uses: actions/upload-artifact@v3
-      #   with:
-      #     name: .coverage
-      #     path: .coverage
-
-      - name: Run Tests
+      - name: Calculate Test Coverage
         env:
           SAAS_HOST: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_HOST }}
           SAAS_ACCOUNT_ID: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID }}
           SAAS_PAT: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_PAT }}
-        run:
-          poetry run pytest test
+        run: poetry run nox -s coverage -- -m "not saas" --db-version ${{ matrix.exasol-version }}
 
-      - name: Fail, if SaaS tests are not activated
-        if: "!contains(github.event.head_commit.message, '[run-saas-tests]') && (matrix.python-version == '3.10')"
-        run: |
-          echo "Failed because the SaaS tests are not activated"
-          exit 1
+      - name: Upload Artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: .coverage
+          path: .coverage
+
+      # - name: Fail, if SaaS tests are not activated
+      #   if: "!contains(github.event.head_commit.message, '[run-saas-tests]') && (matrix.python-version == '3.10')"
+      #   run: |
+      #     echo "Failed because the SaaS tests are not activated"
+      #     exit 1
