#7 Running tests without SaaS

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -27,8 +27,8 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        # python-version: ["3.8", "3.9", "3.10", "3.11"]
-        python-version: ["3.10"]
+        python-version: ["3.8", "3.9", "3.10", "3.11"]
+        # python-version: ["3.10"]
         exasol-version: ["7.1.9"]
 
     steps:
@@ -40,11 +40,16 @@ jobs:
         with:
           python-version: ${{ matrix.python-version }}
 
-      - name: Calculate Test Coverage
+      - name: Calculate Test Coverage with SaaS
+        if: "contains(github.event.head_commit.message, '[run-saas-tests]') && (matrix.python-version == '3.10')"
         env:
           SAAS_HOST: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_HOST }}
           SAAS_ACCOUNT_ID: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID }}
           SAAS_PAT: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_PAT }}
+        run: poetry run nox -s coverage -- -- --db-version ${{ matrix.exasol-version }}
+
+      - name: Calculate Test Coverage without SaaS
+        if: "!contains(github.event.head_commit.message, '[run-saas-tests]') || (matrix.python-version != '3.10')"
         run: poetry run nox -s coverage -- -- -m "not saas" --db-version ${{ matrix.exasol-version }}
 
       - name: Upload Artifacts
@@ -53,8 +58,8 @@ jobs:
           name: .coverage
           path: .coverage
 
-      # - name: Fail, if SaaS tests are not activated
-      #   if: "!contains(github.event.head_commit.message, '[run-saas-tests]') && (matrix.python-version == '3.10')"
-      #   run: |
-      #     echo "Failed because the SaaS tests are not activated"
-      #     exit 1
+      - name: Fail, if SaaS tests are not activated
+        if: "!contains(github.event.head_commit.message, '[run-saas-tests]') && (matrix.python-version == '3.10')"
+        run: |
+          echo "Failed because the SaaS tests are not activated"
+          exit 1
